# Site settings
title: RubyOnRails developers workshop
email: info@ict4g.org
description: > # this means to ignore newlines until "baseurl:"
  Some days of RubyOnRails development around the Eastern Cape.
  By the ICT4G FBK guys.
baseurl: "/ror-dw-2015" # the subpath of your site, e.g. /blog/
url: "http://ict4g.github.io/ror-dw-2015" # the base hostname & protocol for your site
twitter_username: ict4g_fbk
github_username:  ict4g

# Build settings
markdown: kramdown
